import { renderToStaticMarkup } from 'react-dom/server';
import {
    LandingPageConfig,
    SectionType,
    HeroSection as HeroSectionType,
    SocialProofSection as SocialProofSectionType,
    ContactSection as ContactSectionType,
    FeaturesSection as FeaturesSectionType,
    GallerySection as GallerySectionType,
    CarouselSection as CarouselSectionType,
    TestimonialsSection as TestimonialsSectionType,
    CtaSection as CtaSectionType,
    FAQSection as FaqSectionType,
    PricingSection as PricingSectionType,
    FooterSection as FooterSectionType
} from '../types';
import { HeroSection } from '../components/sections/HeroSection';
import { SocialProofSection } from '../components/sections/SocialProofSection';
import { ContactSection } from '../components/sections/ContactSection';
import { FeaturesSection } from '../components/sections/FeaturesSection';
import { GallerySection } from '../components/sections/GallerySection';
import { CarouselSection } from '../components/sections/CarouselSection';
import { TestimonialsSection } from '../components/sections/TestimonialsSection';
import { CtaSection } from '../components/sections/CtaSection';
import { FaqSection } from '../components/sections/FaqSection';
import { PricingSection } from '../components/sections/PricingSection';
import { FooterSection } from '../components/sections/FooterSection';

export function generateHTML(config: LandingPageConfig): string {
    const { sections, design, name } = config;
    const { primaryColor, secondaryColor, fontFamily } = design;

    // Normalize and sort sections (matching LivePreview logic)
    const sortedSections = [...sections].map(s => ({
        ...s,
        type: s.type.replace(/Section$/i, '').toLowerCase() as SectionType
    })).sort((a, b) => a.order - b.order);

    const SectionsMarkup = () => (
        <>
            {sortedSections.map((section) => {
                switch (section.type) {
                    case 'hero':
                        return <HeroSection key={section.id} section={section as HeroSectionType} primaryColor={primaryColor} />;
                    case 'social-proof':
                        return <SocialProofSection key={section.id} section={section as SocialProofSectionType} primaryColor={primaryColor} />;
                    case 'faq':
                        return <FaqSection key={section.id} section={section as FaqSectionType} primaryColor={primaryColor} />;
                    case 'pricing':
                        return <PricingSection key={section.id} section={section as PricingSectionType} primaryColor={primaryColor} />;
                    case 'contact':
                        return <ContactSection key={section.id} section={section as ContactSectionType} primaryColor={primaryColor} />;
                    case 'features':
                        return <FeaturesSection key={section.id} section={section as FeaturesSectionType} primaryColor={primaryColor} />;
                    case 'gallery':
                        return <GallerySection key={section.id} section={section as GallerySectionType} primaryColor={primaryColor} />;
                    case 'carousel':
                        return <CarouselSection key={section.id} section={section as CarouselSectionType} primaryColor={primaryColor} />;
                    case 'testimonials':
                        return <TestimonialsSection key={section.id} section={section as TestimonialsSectionType} primaryColor={primaryColor} />;
                    case 'cta':
                        return <CtaSection key={section.id} section={section as CtaSectionType} primaryColor={primaryColor} />;
                    case 'footer':
                        return <FooterSection key={section.id} section={section as FooterSectionType} primaryColor={primaryColor} />;
                    default:
                        return null;
                }
            })}
        </>
    );

    const bodyContent = renderToStaticMarkup(<SectionsMarkup />);

    return `<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${name}</title>
    <meta name="description" content="Landing page generated by LP Generator">

    <!-- Tailwind CSS -->
    <script src="https://cdn.tailwindcss.com"></script>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet">

    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        primary: '${primaryColor}',
                        secondary: '${secondaryColor}',
                    },
                    fontFamily: {
                        sans: ['${fontFamily || 'Inter'}', 'sans-serif'],
                    }
                }
            }
        }
    </script>

    <style>
        /* Base Animations */
        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }
        @keyframes slideUp {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
        }
        @keyframes scaleIn {
            from { opacity: 0; transform: scale(0.95); }
            to { opacity: 1; transform: scale(1); }
        }

        .animate-fade-in { animation: fadeIn 0.8s ease-out forwards; }
        .animate-slide-up { animation: slideUp 0.8s ease-out 0.2s forwards; opacity: 0; }
        .animate-scale-in { animation: scaleIn 0.5s ease-out forwards; }

        /* Custom Scrollbar */
        ::-webkit-scrollbar {
            width: 8px;
        }
        ::-webkit-scrollbar-track {
            background: #f1f1f1;
        }
        ::-webkit-scrollbar-thumb {
            background: #cbd5e1;
            border-radius: 4px;
        }
        ::-webkit-scrollbar-thumb:hover {
            background: #94a3b8;
        }
    </style>
</head>
<body class="bg-white font-sans text-gray-900 antialiased selection:bg-primary/20 selection:text-primary">
    ${bodyContent}

    <!-- Script para interações básicas (Faq, Mobile Menu) -->
    <script>
        // Simple script to handle interactions if needed in exported HTML
        document.addEventListener('DOMContentLoaded', () => {
            // FAQ Accordion
            const details = document.querySelectorAll('details');
            details.forEach((targetDetail) => {
                targetDetail.addEventListener('click', () => {
                    // Optional: Close others
                });
            });
        });
    </script>
</body>
</html>`;
}
